version: 1
validation: sovereign
accounts:
  - name: alice
    coins:
      - 20000odis
      - 20000000000uodis
  - name: bob
    coins:
      - 20000odis
      - 20000000000uodis
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 5odis
    - 100000uodis
validators:
  - name: alice
    bonded: 100000000uodis
genesis:
  app_state:
    staking:
      params:
        bond_denom: "uodis"
